### ISSUE TITLE
cannot get or set values to a 'Memcached' type bucket

### ISSUE THREAD

**Issue by leprechau** [couchbase/go-couchbase#37]
Using the following stub code below against a cluster with a 'Memcached' type bucket called 'memcached_bucket' I get the following error everytime I try to read or write a value:

```
ahurt1:local ahurt$ go build cb-test.go; ./cb-test
2015/03/16 17:08:05 Error setting key: go-couchbase: vbmap smaller than vbucket list: 6536 vs. []
```

Thank you in advance!

```go
package main

import (
	"bytes"
	"github.com/couchbase/go-couchbase"
	"log"
)

const (
	CB_HOST   = "http://some-host:8091/"
	CB_BUCKET = "memcached_bucket"
)

func main() {
	c, err := couchbase.Connect(CB_HOST)
	if err != nil {
		log.Fatalf("Error connecting:  %v", err)
	}

	pool, err := c.GetPool("default")
	if err != nil {
		log.Fatalf("Error getting pool:  %v", err)
	}

	bucket, err := pool.GetBucket(CB_BUCKET)
	if err != nil {
		log.Fatalf("Error getting bucket:  %v", err)
	}

	buff := bytes.NewBufferString("someValue")

	err = bucket.SetRaw("someKey", 0, buff.Bytes())
	if err != nil {
		log.Fatalf("Error setting key: %v", err)
	}
}
```

**Comment by leprechau** [comment]
Found this on the Couchbase issue tracker thanks to macpaddy@freenode.

https://issues.couchbase.com/browse/GOCBC-22

**Comment by maniktaneja** [comment]
go-couchbase doesn't currently support memcached buckets.  You can try using the stubs in couchbase/gomemcached, set the value of vb (vbucket) to 0 and you should be able to get/set values to the memcached bucket directly. 

Also the link that you have posted is for a different project.

**Comment by leprechau** [comment]
Thank you for the response, I'll look into that.  On the different projects, I see that the github page for 'gocb' references this project as a 'prototype' ... are they both still active or should I switch over to 'gocb'?

Thank you again for the response.

**Comment by maniktaneja** [comment]
gocb I believe is still under development.

**Comment by jmcgill0brightcove** [comment]
Please add memcache bucket support.

**Comment by maniktaneja** [comment]
Can you try couchbase/gomemcached  ? That should work with memcached buckets.

**Comment by leprechau** [comment]
There is some activity on this in the gocb project ...

https://issues.couchbase.com/browse/GOCBC-23
and
http://review.couchbase.org/#/c/57882/
