### ISSUE TITLE
Questions on bulk operations

### ISSUE THREAD

**Issue by tleyden** [couchbase/go-couchbase#42]
I noticed there was a BulkGet but no corresponding BulkSet.  Any reason for that or is it just not commonly needed?

Also for the BulkGet, is the main motivation to allow more efficient throughput by reducing round trips, or just an easier api to use?  

/cc @steveyen @adamcfraser

**Comment by maniktaneja** [comment]
BulkSets breaks the atomicity model for couchbase , if the set for one of keys fails it may not be possible to rollback the entire operation. We need a multi-key lock implementation before we can attempt a safe multiSet, that’s the hard bit :).

Yes, bulkGets will reduce round-trips, so wherever possible you should use this api.

Cheers,
Manik

**Comment by tleyden** [comment]
Awesome, thanks @maniktaneja.  Might fire off some more questions, want them in github so I can find them later.
