### ISSUE TITLE
How to change a value of beam.smp in couchbase

### ISSUE THREAD

**Issue by Gnanodhar** [couchbase/go-couchbase#77]
Hello,

I could find some info from couchbase page
Excessive memory consumption by the beam.smp process on Lnux
If the XDCR Max Replications per Bucket value is raised (such as to 128), then the beam.smp process uses excessive memory. The solution is to reset to 32 or lower.

I could see some beam.smp errors .. I just want to change or see the value of beam.smp for my couchbase server..

Can anyone let me know how to find the value of beam.smp

Thanks,
Dev

**Comment by tleyden** [comment]
This isn't a go-couchbase issue either.  As mentioned in https://github.com/couchbase/sync_gateway/issues/2215, can you post to the https://forums.couchbase.com/ instead?  Or you if you have an enterprise license you might want to reach out to support directly.
